stages:
  - test

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: runner
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: hunter2
  POSTGRES_HOST: postgres

test_code:
  image: python:3.8
  script:
    - apt-get update && apt-get install -y sqlite3
    - pip3 install -r requirements.txt
    - python3 -m unittest discover
  stage: test

test_style:
  image: python:3.8
  script:
    - pip3 install flake8
    - flake8 src
  stage: test

test_types:
  image: python:3.8
  script:
    - pip3 install mypy
    - mypy src
  stage: test